---
- name: Check installed Ruby
  shell: rbenv versions | grep $(rbenv install -l | grep -v - | tail -1)
  changed_when: False
  failed_when: False
  register: ruby_status

- name: Install Ruby
  shell: rbenv install $(rbenv install -l | grep -v - | tail -1)
  when: ruby_status|failed

- name: Register global Ruby version
  shell: rbenv global $(rbenv install -l | grep -v - | tail -1)
  tags:
    - ruby

- name: Install gems
  shell: rbenv exec gem install {{ item }}
  with_items: ruby_install_gems
  tags:
    - ruby
